### ISSUE TITLE
Theme Tile Resizing

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/csh-material-login#3]
Right now when you have a theme tile where either the author or theme name itself gets longer than the average, the theme pushes the blocks around a little unintuitively.

![Name Issues](https://csh.rit.edu/~matted/images/Issueswithnames.png)

**Comment by stevenmirabito** [comment]
I think the best way to fix this is to just hide overflow on the ThemeInfo component. For simplicity we're not rendering individual rows for each group of 4, and there isn't a good way to accommodate cards with different heights without doing so.
